# Generated by Django 5.0.6 on 2024-05-28 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect4Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.TextField(default='[["", "", "", "", "", "", ""], ... ]')),
                ('current_colour', models.CharField(default='R', max_length=1)),
                ('winner', models.IntegerField()),
                ('status', models.CharField(default='playing', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoughtsAndCrossesSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.TextField(default='[["", "", ""], ... ]')),
                ('current_shape', models.CharField(default='X', max_length=1)),
                ('winner', models.IntegerField()),
                ('status', models.CharField(default='playing', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
