# Generated by Django 5.0.6 on 2024-05-23 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('realms', '0001_initial'), ('realms', '0002_alter_realm_id'), ('realms', '0003_remove_realm_settings')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('property_limit', models.IntegerField(default=3)),
                ('seats', models.IntegerField(default=5)),
                ('soft_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
